var a = 10;
var b = 20;
console.log(typeof a);
console.log(typeof "name");
console.log(typeof ["name", "ndsg"]);
console.log(typeof 7.9);
console.log(typeof true);
console.log(typeof undefined);
console.log(typeof null);
console.log(typeof {});
console.log(typeof []);